_wandb:
    value:
        cli_version: 0.21.1
        e:
            vwjqzywvkv0whjdsbaktuz0g1wtwzvqw:
                args:
                    - --model
                    - GNN
                    - --epochs
                    - "3"
                codePath: Scripts/model_trainer.py
                codePathLocal: model_trainer.py
                cpu_count: 40
                cpu_count_logical: 80
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "200315998208"
                        used: "23568736256"
                email: mistakesweremaed@gmail.com
                executable: /home/nhn479/.conda/envs/Lightning/bin/python
                git:
                    commit: a5c436d5b4c48ba439b3b765b86b8553dc4dd576
                    remote: https://github.com/MistakesWereMaed/OceanPredict.git
                gpu: Tesla V100S-PCIE-32GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "34359738368"
                      name: Tesla V100S-PCIE-32GB
                      uuid: GPU-7a2696df-0422-39b0-9a5f-2e8699a715ad
                host: gpu001
                memory:
                    total: "404260638720"
                os: Linux-4.18.0-513.5.1.el8_9.x86_64-x86_64-with-glibc2.28
                program: /home/nhn479/Projects/OceanPredict/Scripts/model_trainer.py
                python: CPython 3.10.18
                root: .
                slurm:
                    cluster_name: arc_cluster
                    conf: /etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000020000000002
                    cpu_bind_list: "0x00000000020000000002"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "2"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: nhn479
                    job_cpus_per_node: "2"
                    job_end_time: "1755668581"
                    job_gid: "1477399387"
                    job_id: "140796"
                    job_name: bash
                    job_nodelist: gpu001
                    job_num_nodes: "1"
                    job_partition: gpu1v100
                    job_qos: normal
                    job_start_time: "1755663181"
                    job_uid: "1477399387"
                    job_user: nhn479
                    jobid: "140796"
                    launch_node_ipaddr: 192.168.1.5
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gpu001
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "42589"
                    pty_win_col: "204"
                    pty_win_row: "13"
                    script_context: prolog_task
                    srun_comm_host: 192.168.1.5
                    srun_comm_port: "37385"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "37385"
                    step_nodelist: gpu001
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /home/nhn479/Projects/OceanPredict
                    submit_host: login001
                    task_pid: "1837687"
                    tasks_per_node: "1"
                    topology_addr: gpu001
                    topology_addr_pattern: node
                    umask: "0077"
                startedAt: "2025-08-20T04:51:42.511738Z"
                writerId: vwjqzywvkv0whjdsbaktuz0g1wtwzvqw
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 54
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 53
                - 54
                - 77
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.2
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 8
hidden_dim:
    value: 64
image_size:
    value:
        - 157
        - 337
learning_rate:
    value: 0.0001
num_gnn_layers:
    value: 1
